namespace Eman.Application.Modules.MasterData.BusinessPartners.DoiTacKinhDoanh.Dtos;

public sealed record DoiTacKinhDoanhDto(
    Guid Id,
    string MaDoiTac,
    string TenDoiTac,
    Guid LoaiDoiTacId,
    string MaLoaiDoiTac,
    string TenLoaiDoiTac,
    bool LaNhaCungCap,
    string? MaSoThue,
    string? DiaChi,
    string? NguoiLienHe,
    string? DienThoai,
    string? Email,
    string? SoTaiKhoan,
    string? TenNganHang,
    Guid? DieuKienThanhToanId,
    string? MaDieuKienThanhToan,
    string? TenDieuKienThanhToan,
    Guid? DieuKienGiaoHangId,
    string? MaDieuKienGiaoHang,
    string? TenDieuKienGiaoHang,
    byte TrangThai,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string RowVersion);
